services:
  rustfs:
    container_name: rustfs-storage
    ports:
        - 9002:9000
        - 9001:9001
    volumes:
        - /mnt/rustfs/data:/data
    environment:
        - RUSTFS_ACCESS_KEY=rustfsadmin
        - RUSTFS_SECRET_KEY=rustfsadmin
        - RUSTFS_CONSOLE_ENABLE=true
    image: rustfs/rustfs:latest
    command: --address :9000 --console-enable --server-domains example.com
        --access-key rustfsadmin --secret-key rustfsadmin /data
    networks:
      iceberg_net:

  db:
    container_name: postgres
    image: postgres:17.2
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres"]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 10s
    networks:
      iceberg_net:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'exec 3<>/dev/tcp/127.0.0.1/8080;echo -e "GET /realms/master/.well-known/openid-configuration HTTP/1.1\r\nhost: 127.0.0.1:8080\r\nConnection: close\r\n\r\n" >&3;grep "jwks_uri"  <&3',
        ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 60s
    #ports:
    #  - "8080:8080"
      #  - "30080:8080"
    command:
      [
        "start-dev",
        "--metrics-enabled=true",
        "--health-enabled=true",
        "--import-realm",
        "--verbose",
        "--log-level=INFO",
        "--features=token-exchange",
      ]
    ports:
      - "30080:8080"
    networks:
      iceberg_net:

  openfga-db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
    command: -c 'max_connections=500'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres"]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 10s
    ports:
      - "2346:5432"
    networks:
      iceberg_net:

  openfga-migrate:
    image: openfga/openfga:v1.14
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:postgres@openfga-db:5432/postgres?sslmode=disable
    networks:
      iceberg_net:
    depends_on:
      openfga-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  openfga:
    depends_on:
      openfga-db:
        condition: service_healthy
      openfga-migrate:
        condition: service_completed_successfully
    image: openfga/openfga:v1.14
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:postgres@openfga-db:5432/postgres?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=200
      - OPENFGA_DATASTORE_MAX_IDLE_CONNS=100
      - OPENFGA_PLAYGROUND_ENABLED=false
      - OPENFGA_AUTHN_METHOD=oidc
      - OPENFGA_AUTHN_OIDC_ISSUER=http://keycloak:8080/realms/iceberg
      - OPENFGA_AUTHN_OIDC_ISSUER_ALIASES=http://localhost:30080/realms/iceberg
      - OPENFGA_AUTHN_OIDC_AUDIENCE=openfga
      - OPENFGA_HTTP_TLS_ENABLED=false
      - OPENFGA_CACHE_CONTROLLER_ENABLED=true
      - OPENFGA_CHECK_QUERY_CACHE_ENABLED=true
      - OPENFGA_CHECK_ITERATOR_CACHE_ENABLED=true
    networks:
      iceberg_net:
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081"]
      interval: 5s
      timeout: 30s
      retries: 3
    ports:
      - "35082:8081"
networks:
  iceberg_net:

