services:
  rustfs:
    container_name: rustfs-storage
    ports:
        - 9002:9000
        - 9001:9001
    volumes:
        - /mnt/rustfs/data:/data
    environment:
        - RUSTFS_ACCESS_KEY=rustfsadmin
        - RUSTFS_SECRET_KEY=rustfsadmin
        - RUSTFS_CONSOLE_ENABLE=true
    image: rustfs/rustfs:latest
    command: --address :9000 --console-enable --server-domains example.com
        --access-key rustfsadmin --secret-key rustfsadmin /data
  db:
    container_name: postgres
    image: postgres:17.2
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres"]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 10s

